name: CI

on: [ push ]

jobs:

  lint:

    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/ci

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: ci
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      -
        name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: '1'
      -
        name: Install ruby 3.3.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      -
        name: "Test / Unit Tests (controllers, models, helpers, mailers, jobs, lib, requests)"
        run: bin/bundle exec rspec spec --exclude-pattern "spec/system/**/*_spec.rb"
      -
        name: "Prepare System Tests"
        run: |
          bin/rails db:environment:set RAILS_ENV=test
          bin/rails db:drop db:create db:schema:load
          bin/rails db:migrate
          bin/rails assets:precompile
      -
        name: "Test / System Tests"
        run: TEST_BROWSER=headless_chrome bin/bundle exec rspec spec/system
      -
        name: "Security / brakeman"
        run: |
          gem install brakeman
          brakeman --exit-on-warn --no-progress --color --output /dev/stdout
      -
        name: "Security / bundle-audit"
        run: |
          gem install bundle-audit
          bundle-audit check --update -v
